#!/bin/bash
#PBS -P trial_training_classification
#PBS -j oe
#PBS -N train_on_volta_login
#PBS -q volta_login
#PBS -l select=1:ncpus=5:mem=60gb:ngpus=1
#PBS -l walltime=01:00:00

cd #PBS_O_WORKDIR;
np=$(cat ${PBS_NODEFILE} | wc -l);

source /etc/profile.d/rec_modules.sh

module load miniconda
bash
. ~/.bashrc

conda activate /home/svu/gpenny/.conda/miniconda/4.9/envs/testenv
python ~/Projects/classy/transformer_classifier/train_transformer.py
